language: crystal
dist: xenial

env:
  - DATABASE_URL=postgres://postgres@localhost/shards_info_test

before_script:
  - psql -c 'create database shards_info_test;' -U postgres
  - crystal src/db.cr -- migrate

script:
  - crystal spec
  - crystal tool format --check

services:
  - postgresql
  - redis-server
