language: crystal
dist: xenial

crystal:
  - latest
  - nightly

before_script:
  - psql -c 'create database shards_info_test;' -U postgres
  - crystal src/db.cr migrate

script:
  - crystal spec
  - crystal tool format --check

jobs:
  allow_failures:
  - crystal: nightly

services:
  - postgresql
  - redis-server
