default: &default
  host: localhost
  user: postgres
  password: ''
  adapter: postgres
  skip_dumping_schema_sql: true

development:
  <<: *default
  db: shards_info_development

test:
  <<: *default
  db: shards_info_test

production:
  <<: *default
  db: shards_info_production
