name: Crystal CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check format
        run: crystal tool format --check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal: ["crystallang/crystal", "crystallang/crystal:nightly"]
    container: ${{ matrix.crystal }}
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `shard.yml` file
      - name: Install dependencies
        run: shards install --ignore-crystal-version

      - name: Run tests
        run: crystal spec
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/shards_info_test
          KEMAL_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
